# Generated by Django 5.0.6 on 2025-07-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAKERY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
