# Generated by Django 5.0.6 on 2025-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAKERY', '0004_product_description_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
