# Generated by Django 5.0.6 on 2025-07-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BAKERY', '0005_product_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='price',
            new_name='prices',
        ),
    ]
