# Generated by Django 5.0.6 on 2025-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAKERY', '0007_delete_destination_remove_product_image_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
